/* ── CAR DATABASE ──────────────────── */
const CAR_DATA = {
  'BMW':            ['1 Series','2 Series','3 Series','4 Series','5 Series','6 Series','7 Series','8 Series','X1','X2','X3','X4','X5','X6','X7','XM','M2','M3','M4','M5','M8','i3','i4','i5','i7','iX'],
  'Mercedes-Benz':  ['A-Class','B-Class','C-Class','E-Class','S-Class','CLA','CLS','G-Class','GLA','GLB','GLC','GLE','GLS','AMG GT','EQS','EQE','Maybach S-Class','Maybach GLS'],
  'Audi':           ['A1','A3','A4','A5','A6','A7','A8','Q2','Q3','Q5','Q7','Q8','RS3','RS4','RS5','RS6','RS7','R8','e-tron','e-tron GT','Q4 e-tron'],
  'Porsche':        ['911','718 Cayman','718 Boxster','Cayenne','Macan','Panamera','Taycan'],
  'Toyota':         ['Camry','Corolla','Yaris','C-HR','RAV4','Highlander','Land Cruiser 200','Land Cruiser 300','Land Cruiser Prado','Fortuner','Hilux','Supra','bZ4X'],
  'Lexus':          ['ES','IS','GS','LS','NX','RX','GX','LX','UX','LC','RC'],
  'Honda':          ['Civic','Accord','CR-V','HR-V','Pilot','Passport','Ridgeline','Jazz'],
  'Nissan':         ['Micra','Juke','Qashqai','X-Trail','Murano','Pathfinder','Patrol','Navara','370Z','GT-R','Leaf','Ariya'],
  'Infiniti':       ['Q50','Q60','Q70','QX30','QX50','QX55','QX60','QX80'],
  'Mitsubishi':     ['Lancer','Eclipse Cross','ASX','Outlander','Outlander Sport','Pajero','Pajero Sport','L200'],
  'Subaru':         ['Impreza','Legacy','Outback','Forester','XV','Crosstrek','Ascent','WRX','BRZ'],
  'Mazda':          ['2','3','6','MX-5','CX-3','CX-30','CX-5','CX-60','CX-9'],
  'Kia':            ['Rio','Cerato','K5','Stinger','Seltos','Sportage','Sorento','Telluride','Carnival','EV6','Niro'],
  'Hyundai':        ['Solaris','Elantra','i30','Sonata','Venue','Creta','Tucson','Santa Fe','Palisade','Staria','IONIQ 5','IONIQ 6'],
  'Volkswagen':     ['Polo','Golf','Jetta','Passat','Arteon','T-Roc','Tiguan','Touareg','Multivan','ID.3','ID.4'],
  'Skoda':          ['Fabia','Octavia','Superb','Enyaq','Kamiq','Karoq','Kodiaq'],
  'Range Rover':    ['Evoque','Velar','Sport','Vogue'],
  'Land Rover':     ['Discovery','Discovery Sport','Defender','Freelander'],
  'Volvo':          ['S60','S90','V60','V90','XC40','XC60','XC90','C40'],
  'Jeep':           ['Renegade','Compass','Cherokee','Grand Cherokee','Wrangler','Gladiator'],
  'Ford':           ['Fiesta','Focus','Mondeo','Mustang','EcoSport','Kuga','Edge','Explorer','Expedition','Ranger','F-150','Bronco'],
  'Chevrolet':      ['Spark','Cruze','Malibu','Camaro','Equinox','Traverse','Tahoe','Suburban','Silverado','Colorado','Blazer'],
  'Jaguar':         ['XE','XF','XJ','E-Pace','F-Pace','I-Pace','F-Type'],
  'Tesla':          ['Model 3','Model S','Model X','Model Y','Cybertruck'],
  'Bentley':        ['Continental GT','Flying Spur','Bentayga','Mulsanne'],
  'Rolls-Royce':    ['Ghost','Phantom','Cullinan','Wraith','Dawn'],
  'Ferrari':        ['296 GTB','Roma','Portofino','SF90 Stradale','F8 Tributo','812 Superfast','Purosangue'],
  'Lamborghini':    ['Huracan','Urus','Revuelto'],
  'Maserati':       ['Ghibli','Quattroporte','Levante','GranTurismo','Grecale'],
  'Alfa Romeo':     ['Giulia','Stelvio','Tonale'],
  'Cadillac':       ['CT4','CT5','Escalade','XT4','XT5','XT6'],
  'Dodge':          ['Challenger','Charger','Durango','RAM 1500'],
  'Acura':          ['TLX','MDX','RDX'],
  'Suzuki':         ['Swift','Vitara','SX4','Jimny','Grand Vitara'],
  'Renault':        ['Logan','Sandero','Duster','Kaptur','Arkana','Koleos'],
  'Peugeot':        ['208','308','408','508','2008','3008','5008'],
  'Citroën':        ['C3','C4','C5 X','Berlingo'],
  'Lada':           ['Granta','Vesta','Vesta Cross','XRAY','XRAY Cross','Niva Legend','Niva Travel','Largus'],
  'UAZ':            ['Patriot','Hunter','Pickup','Буханка'],
  'GAZ':            ['Gazelle Next','Sobol'],
  'Haval':          ['Jolion','F7','F7x','H6','H9','Dargo','Dargo X'],
  'Chery':          ['Tiggo 4 Pro','Tiggo 7 Pro','Tiggo 8 Pro','Tiggo 8 Pro Max','Arrizo 8'],
  'Exeed':          ['TXL','RX','VX','LX'],
  'Geely':          ['Atlas Pro','Coolray','Tugella','Emgrand'],
  'Omoda':          ['C5','S5'],
  'BYD':            ['Seal','Han','Atto 3','Song Plus','Tang'],
  'Li Auto':        ['L7','L8','L9'],
};
